services:
  automation_api:
    build: .
    ports:
      - "80:80"
    volumes:
      - type: bind
        source: /etc/salt/
        target: /etc/salt/
      - type: bind
        source: /srv/salt/
        target: /srv/salt/
